version: '3.9'

services:
  postgres-core:
    image: postgres:15.5
    container_name: postgres-core
    environment:
      POSTGRES_DB: core-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    profiles: ["dev_front", "dev_back"]
    ports:
      - "5432:5432"
    volumes:
      - ./back/brm-core/migrations/:/docker-entrypoint-initdb.d/
      - core-data:/var/lib/postgresql/data

  brm-core:
    build:
      context: back/brm-core
      dockerfile: Dockerfile
    command: ./brm-core-app
    profiles: ["dev_front"]
    ports:
      - "50000:50000"
    depends_on:
      - postgres-core

  transport-api:
    build:
      context: back/transport-api
      dockerfile: Dockerfile
    command: ./transport-api-app
    profiles: ["dev_front"]
    ports:
      - "8090:8090"
    depends_on:
      - brm-core

volumes:
  core-data:
