"postgres-leads":
  "username": "root"
  "host": "localhost"
  "port": 5503
  "dbname": "leads-db"
  "sslmode": "disable"

"grpc-core-client":
  "host": "localhost"
  "port": 50000

"grpc-ads-client":
  "host": "localhost"
  "port": 50002

"grpc-notifications-client":
  "host": "localhost"
  "port": 50005

"grpc-server":
  "network": "tcp"
  "port": 50003
