"grpc-clients":
  "core":
    "host": "localhost"
    "port": 50000
  "ads":
    "host": "localhost"
    "port": 50002
  "leads":
    "host": "localhost"
    "port": 50003
  "stats":
    "host": "localhost"
    "port": 50004

"http-server":
  "host": "localhost"
  "port": 8090

"origins":
  "web":
    "host": "localhost"
    "port": 4200
