"grpc-core-client":
  "host": "brm-core"
  "port": 50000

"grpc-ads-client":
  "host": "brm-ads"
  "port": 50002

"grpc-leads-client":
  "host": "brm-leads"
  "port": 50003

"http-server":
  "host": "transport-api"
  "port": 8090

"origins":
  "web":
    "host": "localhost"
    "port": 4200
