// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ads": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает список объявлений с использованием фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Получение списка объявлений",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию/тексту",
                        "name": "pattern",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Поиск по компании",
                        "name": "company_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Поиск по отрасли",
                        "name": "industry",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Сортировка по возрастанию цены",
                        "name": "by_price",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Сортировка по убыванию цены",
                        "name": "by_price_desc",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Сортировка по возрастанию даты создания",
                        "name": "by_date",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Сортировка по убыванию даты создания",
                        "name": "by_date_desc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение объявлений",
                        "schema": {
                            "$ref": "#/definitions/ads.adListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adListResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.adListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет новое объявление",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Добавление нового объявления",
                "parameters": [
                    {
                        "description": "Новое объявление в JSON",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ads.addAdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление объявления",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    }
                }
            }
        },
        "/ads/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает объявление по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Получение объявления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение объявления",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет одно или несколько полей объявления",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Редактирование объявления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ads.updateAdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Безвозвратно удаляет объявление",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Удаление объявления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление объявления",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.adResponse"
                        }
                    }
                }
            }
        },
        "/ads/{id}/response": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаёт отклик у откликнувшейся компании и сделку у владельца объявления",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Откликнуться на объявление",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id объявления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание отклика",
                        "schema": {
                            "$ref": "#/definitions/ads.responseResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.responseResponse"
                        }
                    },
                    "404": {
                        "description": "Объявление не найдено",
                        "schema": {
                            "$ref": "#/definitions/ads.responseResponse"
                        }
                    },
                    "409": {
                        "description": "Попытка откликнуться на объявление своей же компании",
                        "schema": {
                            "$ref": "#/definitions/ads.responseResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.responseResponse"
                        }
                    }
                }
            }
        },
        "/companies/industries": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает словарь из отраслей и их id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Получение отраслей",
                "responses": {
                    "200": {
                        "description": "Успешное получение данных",
                        "schema": {
                            "$ref": "#/definitions/companies.industriesResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.industriesResponse"
                        }
                    }
                }
            }
        },
        "/companies/industries/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает название отрасли по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Получение отрасли по id",
                "responses": {
                    "200": {
                        "description": "Успешное получение данных",
                        "schema": {
                            "$ref": "#/definitions/companies.industriesResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "404": {
                        "description": "Отрасль не найдена",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.industriesResponse"
                        }
                    }
                }
            }
        },
        "/companies/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает поля компании для страницы редактирования",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Получение информации о компании",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id компании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "404": {
                        "description": "Компания не найдена",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет одно или несколько полей компании",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Редактирование полей компании",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id компании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/companies.updateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "404": {
                        "description": "Компания не найдена",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Безвозвратно удаляет компанию и всё, что с этой компанией связано",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Удаление компании",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id компании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление компании",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "404": {
                        "description": "Компания не найдена",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.companyResponse"
                        }
                    }
                }
            }
        },
        "/companies/{id}/mainpage": {
            "get": {
                "description": "Возвращает название и статистику компании для главной страницы",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/companies"
                ],
                "summary": "Получение информации о компании",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id компании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение данных",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    },
                    "404": {
                        "description": "Компания не найдена",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/companies.mainPageResponse"
                        }
                    }
                }
            }
        },
        "/contacts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает список контактов сотрудника с использованием фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/contacts"
                ],
                "summary": "Получение списка контактов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение контактов",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет новый контакт в список контактов сотрудника",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/contacts"
                ],
                "summary": "Добавление нового контакта",
                "parameters": [
                    {
                        "description": "id сотрудника, которого добавляют в контакты",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contacts.addContactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление контакта",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "404": {
                        "description": "Добавляемый сотрудник не найден",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    }
                }
            }
        },
        "/contacts/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает контакт по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/contacts"
                ],
                "summary": "Получение контакта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id контакта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение контакта",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "404": {
                        "description": "Контакт не найден",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет одно или несколько полей контакта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/contacts"
                ],
                "summary": "Редактирование контакта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id контакта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contacts.updateContactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "404": {
                        "description": "Контакт не найден",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Безвозвратно удаляет контакт и все его поля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/contacts"
                ],
                "summary": "Удаление контакта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id контакта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление контакта",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "404": {
                        "description": "Контакт не найден",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/contacts.contactResponse"
                        }
                    }
                }
            }
        },
        "/employees": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает список сотрудников компании с использованием фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/employees"
                ],
                "summary": "Получение списка сотрудников",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Поиск по имени/фамилии",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по должности",
                        "name": "jobtitle",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию отдела",
                        "name": "department",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение сотрудников",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeListResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет нового сотрудника в компанию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/employees"
                ],
                "summary": "Добавление нового сотрудника",
                "parameters": [
                    {
                        "description": "id сотрудника, которого добавляют в контакты",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.addEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление сотрудника",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает сотрудника по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/employees"
                ],
                "summary": "Получение сотрудника",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id сотрудника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение сотрудника",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "404": {
                        "description": "Сотрудник не найден",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет одно или несколько полей сотрудника",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/employees"
                ],
                "summary": "Редактирование сотрудника",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id сотрудника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.updateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "404": {
                        "description": "Сотрудник не найден",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Безвозвратно удаляет сотрудника и все его поля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core/employees"
                ],
                "summary": "Удаление сотрудника",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id сотрудника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление контакта",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав для выполнения операции",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "404": {
                        "description": "Сотрудник не найден",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/employees.employeeResponse"
                        }
                    }
                }
            }
        },
        "/leads": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает список сделок с использованием фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Получение списка сделок",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Фильтрация по id ответственного",
                        "name": "responsible",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтрация по статусу",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение сделок",
                        "schema": {
                            "$ref": "#/definitions/leads.leadsListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/leads.leadsListResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/leads.leadsListResponse"
                        }
                    }
                }
            }
        },
        "/leads/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получает сделку по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Получение сделки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id сделки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение сделки",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "404": {
                        "description": "Сделка не найдена",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет одно или несколько полей сделки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Редактирование сделки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id сделки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/leads.updateLeadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав на редактрование сделки",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "404": {
                        "description": "Сделка не найдена",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/leads.leadResponse"
                        }
                    }
                }
            }
        },
        "/responses": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список откликов компании на объявления",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Получение списка откликов на объявления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка",
                        "schema": {
                            "$ref": "#/definitions/ads.responseListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/ads.responseListResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/ads.responseListResponse"
                        }
                    }
                }
            }
        },
        "/statuses": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает мапу со статусами и их id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leads"
                ],
                "summary": "Получение статусов и их id",
                "responses": {
                    "200": {
                        "description": "Успешное получение",
                        "schema": {
                            "$ref": "#/definitions/leads.statusesResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "$ref": "#/definitions/leads.statusesResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/leads.statusesResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Получает список задач с использованием фильтрации и пагинации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получение списка задач",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию/тексту",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Поиск по этапу",
                        "name": "stage",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение задач",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskListResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новую задачу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Добавление новой задачи",
                "parameters": [
                    {
                        "description": "Новая задача в JSON",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tasks.addTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление задачи",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    }
                }
            }
        },
        "/tasks/stages": {
            "get": {
                "description": "Возвращает словарь из этапов и их id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получение этапов задачи",
                "responses": {
                    "200": {
                        "description": "Успешное получение данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.stageResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.stageResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.stageResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Получает задачу по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получение задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение задачи",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Изменяет одно или несколько полей задачи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Редактирование задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые поля",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tasks.updateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Безвозвратно удаляет задачу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Удаление задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление задачи",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат входных данных",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    },
                    "500": {
                        "description": "Проблемы на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/tasks.taskResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ads.adData": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "created_by": {
                    "type": "integer"
                },
                "creation_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "price": {
                    "type": "integer"
                },
                "responsible": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "ads.adListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ads.adData"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "ads.adResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/ads.adData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "ads.addAdRequest": {
            "type": "object",
            "properties": {
                "industry": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "ads.responseData": {
            "type": "object",
            "properties": {
                "ad_id": {
                    "type": "integer"
                },
                "company_id": {
                    "type": "integer"
                },
                "creation_date": {
                    "type": "integer"
                },
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "ads.responseListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ads.responseData"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "ads.responseResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/ads.responseData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "ads.updateAdRequest": {
            "type": "object",
            "properties": {
                "industry": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "responsible": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "companies.companyData": {
            "type": "object",
            "properties": {
                "creation_date": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                }
            }
        },
        "companies.companyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/companies.companyData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "companies.industriesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "companies.mainPageData": {
            "type": "object",
            "properties": {
                "stats": {
                    "$ref": "#/definitions/companies.mainPageStatsData"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "companies.mainPageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/companies.mainPageData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "companies.mainPageStatsData": {
            "type": "object",
            "properties": {
                "active_ads_aount": {
                    "type": "integer"
                },
                "active_leads_amount": {
                    "type": "integer"
                },
                "active_leads_price": {
                    "type": "integer"
                },
                "closed_leads_price": {
                    "type": "integer"
                },
                "company_absolute_rating": {
                    "type": "number"
                },
                "company_relative_rating": {
                    "type": "number"
                },
                "total_leads_amount": {
                    "type": "integer"
                }
            }
        },
        "companies.updateCompanyRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                }
            }
        },
        "contacts.addContactRequest": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "description": "EmployeeId это id сотрудника, которого добавляют в контакты",
                    "type": "integer"
                }
            }
        },
        "contacts.contactData": {
            "type": "object",
            "properties": {
                "creation_date": {
                    "type": "integer"
                },
                "employee": {
                    "$ref": "#/definitions/contacts.employeeData"
                },
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                }
            }
        },
        "contacts.contactResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/contacts.contactData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "contacts.employeeData": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "creation_date": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "job_title": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                }
            }
        },
        "contacts.updateContactRequest": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                }
            }
        },
        "employees.addEmployeeRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "job_title": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                }
            }
        },
        "employees.employeeData": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "creation_date": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "job_title": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                }
            }
        },
        "employees.employeeListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employees.employeeData"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "employees.employeeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/employees.employeeData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "employees.updateEmployeeRequest": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "job_title": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                }
            }
        },
        "leads.leadData": {
            "type": "object",
            "properties": {
                "ad_id": {
                    "type": "integer"
                },
                "client_company": {
                    "type": "integer"
                },
                "client_employee": {
                    "type": "integer"
                },
                "company_id": {
                    "type": "integer"
                },
                "creation_date": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "price": {
                    "type": "integer"
                },
                "responsible": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "leads.leadResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/leads.leadData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "leads.leadsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/leads.leadData"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "leads.statusesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "leads.updateLeadRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "responsible": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "tasks.addTaskRequest": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "integer"
                },
                "responsible_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "tasks.stageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "tasks.taskData": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "created_id": {
                    "type": "integer"
                },
                "deadline": {
                    "type": "integer"
                },
                "responsible_id": {
                    "type": "integer"
                },
                "stage": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "tasks.taskListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tasks.taskData"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "tasks.taskResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/tasks.taskData"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "tasks.updateTaskRequest": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "integer"
                },
                "responsible_id": {
                    "type": "integer"
                },
                "stage": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "BRM API",
	Description:      "Swagger документация к API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
