"postgres-ads":
  "username": "root"
  "host": "localhost"
  "port": 5502
  "dbname": "ads-db"
  "sslmode": "disable"

"grpc-core-client":
  "host": "localhost"
  "port": 50000

"grpc-leads-client":
  "host": "localhost"
  "port": 50003

"grpc-server":
  "network": "tcp"
  "port": 50002
