"postgres-ads":
  "username": "root"
  "host": "postgres-ads"
  "port": 5432
  "dbname": "ads-db"
  "sslmode": "disable"

"grpc-core-client":
  "host": "brm-core"
  "port": 50000

"grpc-leads-client":
  "host": "brm-leads"
  "port": 50003

"grpc-server":
  "network": "tcp"
  "port": 50002
