"postgres-passwords":
  "username": "root"
  "host": "postgres-passwords"
  "port": 5433
  "dbname": "passwords-db"
  "sslmode": "disable"

"redis-tokens":
  "host": "redis-tokens"
  "port": 6000
  "db": 0

"grpc-server":
  "network": "tcp"
  "port": 50001

"http-server":
  "network": "auth"
  "port": 8082

"app":
  "refresh-token-length": 32
  "refresh-token-expiration": 15 * 86400 * 1000000000 # 15 days
  "access-token-expiration": 15 * 3600 * 1000000000 # 15 hours
