"postgres-core":
  "username": "root"
  "host": "postgres-core"
  "port": 40000
  "dbname": "core-db"
  "sslmode": "disable"

"rabbitmq-core":
  "username": "root"
  "host": "rabbitmq-core"
  "port": 14000

  "rabbitmq-shards":
    "amount": 4
    "shard01":
      "producer": "to_core_from_transport_api_01"
      "consumer": "to_transport_api_from_core_01"
    "shard02":
      "producer": "to_core_from_transport_api_02"
      "consumer": "to_transport_api_from_core_02"
    "shard03":
      "producer": "to_core_from_transport_api_03"
      "consumer": "to_transport_api_from_core_03"
    "shard04":
      "producer": "to_core_from_transport_api_04"
      "consumer": "to_transport_api_from_core_04"

"grpc-server":
  "network": "tcp"
  "port": 50000
